export device=cactus # device codename
export telegram="12345:abcd" # Telegram Bot Token
export chat="-1234" # Telegram Chat/Channel Id
export sticker="CAACAgUAAx0CUvrZngABBYwUXk5nQJfMaY7oEw5sD97D5XNhNnsAApEAA2otjDPaQ_65alL0KxgE" #Telegram Sticker Id
export user=wulan17 # Your Username
export email="username@example.com" # Your Email
export rom="KomodOS" # Rom Name
export repo="https://github.com/Komodo-OS-Rom/manifest" # Rom Manifest Url
export branch="ten" # Rom Branch
export vendor="komodo" # Rom Vendor Name
export release_repo="wulan17/pre-release" # Release Repo
export GITHUB_TOKEN="81973" # Github Api Token
export timezone="Asia/Jakarta" # Your Time Zone
export outdir="out/target/product/$device"
